#!/usr/bin/env bash

PORT=8080
NPM_CMD="npm $@";
CONTAINER_NAME="tales--run-npm-task"

if [ "$NPM_CMD" == "npm run dev" ]
then
    # note security issue with disableHostCheck (DNS Rebinding attack)
    # https://github.com/webpack/webpack-dev-server/issues/882#issuecomment-325994310
    NPM_CMD="npm run dev -- --host=0.0.0.0 --disableHostCheck"
    docker run -it --rm -p 127.0.0.1:8080:8080 --name ${CONTAINER_NAME} -v "$PWD":/usr/src/app -w /usr/src/app -u "node" node:8-alpine ${NPM_CMD}
else
    docker run -it --rm --name ${CONTAINER_NAME} -v "$PWD":/usr/src/app -w /usr/src/app -u "node" node:8-alpine ${NPM_CMD}
fi
